=== rhaul/Darklands/file_formats/wallace.net/darklands/xml_formats/file_format.dtd
<!-- Root element: the file -->
<!ELEMENT file (globs?, description, notes?, offsets?, structdefs?, enumerations?, ignore?)>
<!ATTLIST file
	name CDATA #REQUIRED
>

<!-- ====================================================================== -->

<!-- External definitions of a "simple HTML subset" -->
<!ENTITY % SimpleHTML SYSTEM "simple_inline_html.dtd">
%SimpleHTML;

<!-- ====================================================================== -->

<!-- Data types -->

<!ENTITY % BasicVar.Class "char | byte | word | dword | bit">

<!ENTITY % SizableVar.Class "int | string">

<!ENTITY % ContainerVar.Class "struct | array | bitmask">

<!-- All data types (including the unknown object) -->

<!ENTITY % Var.Class "
	%BasicVar.Class; |
	%SizableVar.Class; |
	%ContainerVar.Class; |
	unknown
">

<!-- ====================================================================== -->

<!ENTITY % Describable.Contents "
	description?, notes?
">

<!-- Contents of the basic data types -->
<!ENTITY % BasicVar.Contents "
	( %Describable.Contents; )
">

<!ENTITY % SizableVar.Contents "
	%BasicVar.Contents;
">

<!-- ====================================================================== -->

<!-- Filename glob for instances of this file type -->
<!ELEMENT globs (glob+)>
<!ELEMENT glob EMPTY>
<!ATTLIST glob
	dir CDATA #IMPLIED
	filespec CDATA #REQUIRED
>

<!-- Expected contents at a particular offset -->
<!ELEMENT offsets (offset+)>
<!ELEMENT offset ((%Var.Class;)*)>
<!ATTLIST offset
	start CDATA #REQUIRED
	end CDATA #IMPLIED
>

<!-- Definition of a structure -->
<!ELEMENT structdefs (structdef | external-structdef)+>
<!ELEMENT structdef (%Describable.Contents;, (%Var.Class;)*)>
<!ATTLIST structdef
	type ID #REQUIRED
	description CDATA #IMPLIED
	size CDATA #IMPLIED
>
<!ELEMENT external-structdef EMPTY>
<!ATTLIST external-structdef
	type ID #REQUIRED
	file CDATA #REQUIRED
>

<!-- Definition of an enumeration mapping -->
<!ELEMENT enumerations (enumeration | external-enumeration)+>
<!ELEMENT enumeration (%Describable.Contents;, map*)>
<!ATTLIST enumeration
	type ID #REQUIRED
	description CDATA #IMPLIED
>
<!ELEMENT external-enumeration EMPTY>
<!ATTLIST external-enumeration
	type ID #REQUIRED
	file CDATA #REQUIRED
>

<!--
	Extra text at the end of the file which can be ignored.
	Intended to be used only while still developing a file format document.
-->
<!ELEMENT ignore (#PCDATA)>

<!-- ====================================================================== -->

<!-- Default attributes of all known data types -->
<!ENTITY % Var.Attrib "
	at CDATA #IMPLIED
	name CDATA #IMPLIED
	label NMTOKEN #IMPLIED
	unknown ( yes | no ) #IMPLIED
	constant ( yes | no ) #IMPLIED
	value CDATA #IMPLIED
">

<!-- Attributes of a basic data element -->
<!ENTITY % BasicVar.Attrib "
	%Var.Attrib;
	enumeration NMTOKEN #IMPLIED
">

<!-- Additional attributes of a sizable data element (like 'string') -->
<!ENTITY % SizableVar.Attrib "
	%Var.Attrib;
	size CDATA #IMPLIED
">

<!-- ====================================================================== -->

<!-- Simple (non-container) data types -->

<!ELEMENT char %BasicVar.Contents;>
<!ATTLIST char
	%BasicVar.Attrib; 
>
<!ELEMENT byte %BasicVar.Contents;>
<!ATTLIST byte
	%BasicVar.Attrib; 
>
<!ELEMENT word %BasicVar.Contents;>
<!ATTLIST word
	%BasicVar.Attrib; 
>
<!ELEMENT dword %BasicVar.Contents;>
<!ATTLIST dword
	%BasicVar.Attrib; 
>
<!ELEMENT bit %BasicVar.Contents;>
<!ATTLIST bit
	%BasicVar.Attrib; 
>

<!-- ====================================================================== -->

<!ELEMENT int %SizableVar.Contents;>
<!ATTLIST int
	%SizableVar.Attrib; 
>

<!ELEMENT string %SizableVar.Contents;>
<!ATTLIST string
	%SizableVar.Attrib; 
	enumeration NMTOKEN #IMPLIED
	delimiter CDATA #IMPLIED
>

<!-- ====================================================================== -->

<!-- Container data types -->

<!ELEMENT struct (%Describable.Contents;)>
<!ATTLIST struct
	%BasicVar.Attrib; 
	type IDREF #REQUIRED
>

<!ELEMENT array (%Describable.Contents;, (%Var.Class;))>
<!ATTLIST array
	%BasicVar.Attrib; 
	%SizableVar.Attrib; 
>

<!ELEMENT bitmask (%Describable.Contents;, (bit, bit, bit, bit, bit, bit, bit, bit)+)>
<!ATTLIST bitmask
	%BasicVar.Attrib; 
	%SizableVar.Attrib; 
>

<!-- ====================================================================== -->

<!ELEMENT unknown (%Describable.Contents;, guesses?)>
<!ATTLIST unknown
	at CDATA #IMPLIED
	size CDATA #IMPLIED
	constant (yes | no) #IMPLIED
	value CDATA #IMPLIED
>

<!ELEMENT guesses (guess+)>
<!ELEMENT guess (%Describable.Contents;, (%Var.Class;)*)>

<!-- ====================================================================== -->

<!-- Description (of a file, element, struct, etc) -->
<!ELEMENT description (%html.flow; | reference)*>
<!ATTLIST description
	type (simple | paragraph | extended) #IMPLIED
	xmlns:html CDATA #FIXED "http://www.w3.org/1999/xhtml"
>

<!-- Notes and comments (informal additions to the description) -->
<!ELEMENT notes (note+)>
<!ELEMENT note (#PCDATA | %html.inline; | reference)*>
<!ATTLIST note
	xmlns:html CDATA #FIXED "http://www.w3.org/1999/xhtml"
>

<!-- Reference to an internal or external definition -->
<!ELEMENT reference (#PCDATA)>
<!ATTLIST reference
	file CDATA #IMPLIED
	type CDATA #IMPLIED
	to NMTOKEN #IMPLIED
	label CDATA #IMPLIED
>

<!-- ====================================================================== -->

<!-- A mapping (part of an enumeration) -->
<!ELEMENT map (notes?)>
<!ATTLIST map
	from CDATA #REQUIRED
	to CDATA #REQUIRED
>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/X.imc.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Image catalog files">

<globs>
	<glob filespec="*.imc" />
</globs>

<description type="paragraph">
	Battle sprites animation catalogue.
	Contains 72 frames for walking (WK) or combat (CB) or 16 frames for dying sequence (DY).
	Entire .IMC file is compressed using DL variant od RLE. (see reader_drle.py)
	<html:em>Next passages are describing contents of decompressed file.</html:em>
</description>

<offsets>
	<offset start="0x00">

		<array at="0x00" size="24" unknown="yes">
			<description>Looks like pairs of words. Small numbers. Y/X frame offsets maybe.</description>
			<byte />
		</array>

		<byte at="25" unknown="yes">
			<description>0xff for DY files, 0x0 for other</description>
		</byte>

        <array at="26" size="20" unknown="yes">
            <description>Unknown data. Present only in non-DY files.</description>
            <notes>
                <note>Looks like motion-related. All zeroes for static monsters (M73, M90).</note>
            </notes>
            <byte />
        </array>

		<word at="26/46" name="sprite_height">
			<description>Height of sprite (height of all frames is same)</description>
		</word>

		<array at="28/48" size="8" name="sprite_widths">
			<description>Sprite widths for 8 directions (frames in one direction are having the same width)</description>
			<word />
		</array>

        <array at="44/64" size="16" unknown="yes">
            <description>8 words? Also direction related?</description>
            <byte />
        </array>

		<word at="60/80" name="frame_count">
			<description>Frame count for one direction. File contains 8 * frame_count images.</description>
		</word>

		<word at="62/82" name="data_length">
			<description>Size of the rest of the file beyond the frame offsets.</description>
		</word>

		<array at="64/84" size="variable" name="frame_data_offsets">
			<description>Offsets of frame data</description>
			<notes>
				<note>Starting beyond the end of this array</note>
				<note>Divided by 16 for reason unknown. (so 'end+offset*16' is the start of frame data)</note>
			</notes>
			<word />
		</array>


	</offset>

</offsets>

<!-- ====================================================================== -->

<structdefs>
	<structdef type="frame" size="">

		<byte at="0x00" name="width">
			<description>Width of image</description>
		</byte>
		<byte at="0x01" name="height">
			<description>Height of image</description>
		</byte>

		<array at="0x02" size="variable" name="image_data">
			<byte />
			<description>Encoded image data</description>
			<notes>
				<note>Each row of image starts with byte containing count of defined pixels.</note>
				<note>Next byte containing count of starting empty pixels.</note>
				<note>Then follows count_of_defined_pixels long sequence of pixels (pallete index bytes) to be rendered. (zero is transparent)</note>
				<note></note>
				<note></note>
			</notes>
		</array>
	</structdef>
</structdefs>

</file>

=== rhaul/Darklands/file_formats/wallace.net:80/darklands/xml_formats/structures.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands common structures">

<description>These structures are common to a number of different files.</description>

<structdefs>

	<structdef type="date" size="0x08">
		<description>A date.</description>
		<word at="0x00" name="hour" />
		<word at="0x02" name="day" />
		<word at="0x04" name="month" enumeration="month" />
		<word at="0x06" name="year">
			<notes>
				<note>Contains the entire value (not just 0 for 1400)</note>
			</notes>
		</word>
	</structdef>

	<structdef type="date_reversed" size="0x08">
		<description>A date stored in reversed format.</description>
		<notes>
			<note>
				<reference file="dksaveXX.sav" type="variable" to="curr_date"></reference>
				is stored in this format, although dates in the
				<reference file="dksaveXX.sav" type="structdef" to="event">event structure</reference>
				are stored in the normal
				<reference type="structdef" to="date"></reference> format.
			</note>
		</notes>
		<word at="0x00" name="year">
			<notes>
				<note>Contains the entire value (not just 0 for 1400)</note>
			</notes>
		</word>
		<word at="0x02" name="month" enumeration="month" />
		<word at="0x04" name="day" />
		<word at="0x06" name="hour" />
	</structdef>

	<structdef type="money" size="0x06">
		<description>An amount of money.</description>
		<notes>
			<note>Money is stored with the monetary units separated, rather than simply storing the number of pfenniges.</note>
			<note>Darklands does seem to recover if the number of pfenniges or groschen "overflow", and it makes change automatically.</note>
		</notes>
		<word at="0x00" name="florins" />
		<word at="0x02" name="groschen" />
		<word at="0x04" name="pfenniges" />
	</structdef>

	<structdef type="coordinates" size="0x04">
		<description>A world map location (pair of coordinates).</description>
		<word at="0x00" name="x_coord">
			<description>X-coordinate.</description>
			<notes>
				<note>Ranges from 0x0000 - 0x0147.</note>
				<note>The maximum is the first word of the file "darkland.map".</note>
			</notes>
		</word>
		<word at="0x02" name="y_coord">
			<description>Y-coordinate.</description>
			<notes>
				<note>Ranges from 0x0000 - 0x03a3.</note>
				<note>The maximum is the second word of the file "darkland.map".</note>
			</notes>
		</word>
	</structdef>

	<structdef type="item" size="0x06">
		<description>An item.</description>
		<notes>
			<note>
				Most of these values can be found in the
				<reference type="variable" to="item_definitions" file="darkland.lst">item_definitions array</reference>.
				Quality and quantity, of course, differ from item to item.
			</note>
		</notes>
		<word at="0x00" name="code" />
		<byte at="0x02" name="type" />
		<byte at="0x03" name="quality" />
		<byte at="0x04" name="quantity" />
		<byte at="0x05" name="weight" />
	</structdef>

	<structdef type="attribute_set" size="0x07">
		<description>A set of attribute values.</description>

		<byte at="0x00" name="end">
			<description>Endurance.</description>
		</byte>
		<byte at="0x01" name="str">
			<description>Strength.</description>
		</byte>
		<byte at="0x02" name="agl">
			<description>Agility.</description>
		</byte>
		<byte at="0x03" name="per">
			<description>Perception.</description>
		</byte>
		<byte at="0x04" name="int">
			<description>Intelligence.</description>
		</byte>
		<byte at="0x05" name="chr">
			<description>Charisma.</description>
		</byte>
		<byte at="0x06" name="df">
			<description>Divine favor.</description>
		</byte>
	</structdef>

	<structdef type="skill_set" size="0x13">
		<description>A set of skill values.</description>

		<byte at="0x00" name="wEdg">
			<description>Edged Weapon skill.</description>
		</byte>
		<byte at="0x01" name="wImp">
			<description>Impact Weapon skill.</description>
		</byte>
		<byte at="0x02" name="wFll">
			<description>Flail Weapon skill.</description>
		</byte>
		<byte at="0x03" name="wPol">
			<description>Polearm skill.</description>
		</byte>
		<byte at="0x04" name="wThr">
			<description>Thrown Weapon skill.</description>
		</byte>
		<byte at="0x05" name="wBow">
			<description>Bow skill.</description>
		</byte>
		<byte at="0x06" name="wMsl">
			<description>Missile Weapon skill.</description>
		</byte>
		<byte at="0x07" name="alch">
			<description>Alchemy skill.</description>
		</byte>
		<byte at="0x08" name="relg">
			<description>Religious skill.</description>
		</byte>
		<byte at="0x09" name="virt">
			<description>Virtue skill.</description>
		</byte>
		<byte at="0x0a" name="spkC">
			<description>Speak Common skill.</description>
		</byte>
		<byte at="0x0b" name="spkL">
			<description>Speak Latin skill.</description>
		</byte>
		<byte at="0x0c" name="r_w">
			<description>Read/Write skill.</description>
		</byte>
		<byte at="0x0d" name="heal">
			<description>Healing skill.</description>
		</byte>
		<byte at="0x0e" name="artf">
			<description>Artifice skill.</description>
		</byte>
		<byte at="0x0f" name="stlh">
			<description>Stealth skill.</description>
		</byte>
		<byte at="0x10" name="strw">
			<description>Streetwise skill.</description>
		</byte>
		<byte at="0x11" name="ride">
			<description>Riding skill.</description>
		</byte>
		<byte at="0x12" name="wdws">
			<description>Woodwise skill.</description>
		</byte>
	</structdef>

</structdefs>

<!-- ====================================================================== -->

<enumerations>
	<external-enumeration type="month" file="enumerations" />
</enumerations>

</file>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/cache.tmp.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands current inn cache data">

<globs>
	<glob filespec="cache.tmp" />
</globs>

<description type="extended">
	<html:p>
	This is a temporary file, created when a saved game is loaded.
	TODO: is this also created when a new game is started?  Or when going in and out of battle?
	</html:p>

	<html:p>
	All of the structures in here are defined in the saved game format,
	so only brief descriptions are given here.
	</html:p>
</description>

<offsets>
	<offset start="0x00">
		<byte at="0x00" name="max_cache_slot" constant="yes" value="0x63">
			<notes>
				<note>
					See <reference type="variable" to="max_cache_slot" file="dksaveXX.sav" />.
				</note>
			</notes>
		</byte>

		<byte at="0x01" name="num_caches">
			<notes>
				<note>
					See <reference type="variable" to="num_caches" file="dksaveXX.sav" />.
				</note>
			</notes>
		</byte>

		<array at="0x02" size="0x62" name="cache_offsets">
			<notes>
				<note>
					See <reference type="variable" to="cache_offsets" file="dksaveXX.sav" />.
				</note>
			</notes>
			<word />
		</array>

		<array at="0xc6" size="*num_caches" name="caches">
			<notes>
				<note>
					See <reference type="variable" to="caches" file="dksaveXX.sav" />.
				</note>
			</notes>
			<struct type="cache" />
		</array>
	</offset>
</offsets>

<!-- ====================================================================== -->

<structdefs>
	<external-structdef type="cache" file="dksaveXX.sav" />
</structdefs>

</file>

=== rhaul/Darklands/file_formats/wallace.net:80/darklands/xml_formats/X.cat.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands catalog files">

<globs>
	<glob filespec="*.cat" />
	<glob filespec="bc" />
	<glob filespec="lcastle" />
	<glob filespec="msgfiles" />
</globs>

<description type="paragraph">
	Catalog files are basically a filesystem; each one contains a large set of (usually related) files.
</description>

<offsets>
	<offset start="0x00">
		<word at="0x00" name="num_entries">
			<description>Number of file entries.</description>
		</word>

		<array at="0x02" size="*num_entries" name="entries">
			<description>File entries.</description>
			<struct type="entry" />
		</array>
	</offset>

	<offset start="entry[0].offset">
		<array size="*num_entries" name="contents">
			<description>
				Contents of the files.
			</description>
			<notes>
				<note>
					For a given index, the contents start at
					<reference type="structdef" to="entry">entry[idx].offset</reference>,
					and are 
					<reference type="structdef" to="entry">entry[idx].length</reference> long.
				</note>
			</notes>
			<unknown size="entry[idx].length" />
		</array>
	</offset>

</offsets>

<!-- ====================================================================== -->

<structdefs>
	<structdef type="entry" size="0x18">

		<string at="0x00" size="12" name="filename">
			<description>Name of the file.</description>
			<notes>
				<note>Always in 8.3 format.</note>
				<note>Padded with nulls if the filename is shorter.</note>
			</notes>
		</string>

		<dword at="0x0c" name="timestamp">
			<description>Timestamp of when the file was added to the archive.</description>
			<notes>
				<note>
					This might be something else, but all the values in a single cat file are very close together.
					a00c.cat has a timestamp about a minute before e00c.cat, and this field is about 0x40 (64) higher in e00c.cat.
					That would imply it's a number of seconds since an epoch.
					Additionally, einfo.cat (timestamped half a year earlier) has numbers much smaller.
				</note>
				<note>
					Epoch seems to be around 3/1/1979, although I could be mistaken.  1/1/1980 would make more sense.
				</note>
			</notes>
		</dword>

		<dword at="0x10" name="length">
			<description>Length of the contents.</description>
		</dword>

		<dword at="0x14" name="offset">
			<description>Offset to the contents.</description>
		</dword>

	</structdef>
</structdefs>

</file>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/darkland.snt.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands saint descriptions">

<globs>
	<glob filespec="darkland.snt" />
</globs>

<description>Contains long text descriptions of the saints.</description>

<offsets>
	<offset start="0x00">
		<byte at="0x00" name="num_saints" value="0x88">
			<description>Number of saints.</description>
		</byte>

		<array at="0x01" size="*num_saints" name="saint_descriptions">
			<description>Descriptions of the saints.</description>
			<notes>
				<note>
					The order of saints here matches the order in
					<reference file="darkland.lst" type="variable" to="saint_full_names" />.
				</note>
			</notes>
			<string size="0x168" />
		</array>
	</offset>
</offsets>

<!-- ====================================================================== -->

</file>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/darkland.cty.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands city definitions">

<globs>
	<glob filespec="darkland.cty" />
</globs>

<description type="paragraph">
	Contains names, location names, coordinates, and other data specific to cities.
	Non-city locations are stored in darkland.loc.
</description>

<offsets>
	<offset start="0x00">
		<byte at="0x00" name="num_cities" value="0x5c">
			<description>Number of cities.</description>
		</byte>
		<array at="0x01" size="*num_cities" name="cities">
			<description>City definitions.</description>
			<notes>
				<note>
					The order of these is the "definitive" order, since the full name is the best unique identifier.
				</note>
			</notes>
			<struct type="city" />
		</array>
	</offset>
</offsets>

<!-- ====================================================================== -->

<structdefs>
	<external-structdef type="coordinates" file="structures" />

	<structdef type="city" size="0x26e">
		<string at="0x00" size="32" name="short_name" />
		<string at="0x20" size="32" name="full_name" />
		
		<struct at="0x40" type="city_data" name="city_data" />
		
		<string at="0x6e" size="32" name="leader_name" />
		<string at="0x8e" size="32" name="ruler_name" />

		<string at="0xae" size="32" unknown="yes">
			<notes>
				<note>TODO: is this non-empty ever?  (ditto for other two unknowns)</note>
			</notes>
		</string>

		<string at="0xce" size="32" name="polit_name">
			<description>Name of the political center or town square.</description>
			<notes>
				<note>TODO: describe what empty values look like</note>
			</notes>
		</string>
		<string at="0xee" size="32" name="town_hall_name" />
		<string at="0x10e" size="32" name="fortress_name">
			<description>Name of the city fortress or castle.</description>
		</string>
		<string at="0x12e" size="32" name="cathedral_name" />
		<string at="0x14e" size="32" name="church_name" />
		<string at="0x16e" size="32" name="market_name">
			<description>Name of the marketplace.</description>
		</string>
		<string at="0x18e" size="32" unknown="yes">
			<notes>
				<note>Often contains "Munzenplatz".  Possibly this is "central square name".</note>
			</notes>
		</string>
		<string at="0x1ae" size="32" name="slum_name" />
		<string at="0x1ce" size="32" unknown="yes">
			<notes>
				<note>
					Many places have "Zeughaus", which translates to "armoury";
					others end in "-turm" (tower?) or "-tor" (gate?).
					Quite possible this is for one of the unused "rebellion" codepath.
				</note>
			</notes>
		</string>
		<string at="0x1ee" size="32" name="pawnshop_name">
			<description>Name of the pawnshop.</description>
			<notes>
				<note>All pawnshops are named the same; this is either 'Leifhaus' or is empty.</note>
			</notes>
		</string>
		<string at="0x20e" size="32" name="kloster_name">
			<description>Name of the kloster (church law and administration building).</description>
		</string>
		<string at="0x22e" size="32" name="inn_name" />
		<string at="0x24e" size="32" name="university_name" />
	</structdef>

<!-- ====================================================================== -->

	<structdef type="city_data" size="0x2e">
		<word at="0x00" name="city_size">
			<description>Size of the city.</description>
			<notes>
				<note>Ranges from 3 (small) to 8 (Koln).</note>
			</notes>
		</word>

		<struct at="0x02" type="coordinates" name="entry_coords">
			<description>City location on the map.</description>
		</struct>
		<struct at="0x06" type="coordinates" name="exit_coords">
			<description>Party coordinates when leaving a city.</description>
			<notes>
				<note>
					When you leave a city, you don't exit at the same point as you entered.
					The exit coordinates were (usually) selected so as not to place you in an untenable position (the ocean, trapped by a river loop, etc).
				</note>
			</notes>
		</struct>

		<array at="0x0a" size="4" name="dock_destinations">
			<description>Dock destination cities.</description>
			<notes>
				<note>
					This contains the indices 
					(in the <reference type="variable" to="cities" /> array)
					of the destinations available via the city docks the docks.
				</note>
				<note>
					0xffff is used for "no destination".
					Inland cities have all 0xffffs.
				</note>
			</notes>
			<word />
		</array>

		<word at="0x12" >
			<description>if coastal, side of the river ???[Hamburg] TODO.</description>
			<notes>
				<note>Values are: 0xffff (inland), 0 (north of the river), 1 (south of the river)</note>
				<note>0 and 1 cities are on or near tidal zones (swamps), and may be subject to flooding.</note>
			</notes>
		</word>

		<word at="0x14" constant="yes" value="4" />

		<word at="0x16">
			<description>Pseudo-ordinal.</description>
			<notes>
				<note>
					At first glance, this looks like an ordinal offset running
					from 0 to 0x5b, but 0x18 is missing, and 0x3c repeats.
				</note>
				<note>
					This value is probably not used.
				</note>
			</notes>
		</word>

		<word at="0x18" name="city_type" enumeration="ruler">
			<description>Type of city</description>
		</word>
		<word at="0x1a" unknown="yes">
			<notes>
				<note>0, 1, 2, or 3.</note>
			</notes>
		</word>

		<word at="0x1c" constant="yes" value="0" />

		<bitmask at="0x1e" size="16 bits" name="city_contents">
			<description>Buildings and locations in the city.</description>
			<notes>
				<note>Bits are on iff there is one of that type of building.</note>
			</notes>

			<bit name="is_kloster">
				<description>Is there a kloster?</description>
			</bit>
			<bit name="is_slums">
				<description>Is there a slums?</description>
			</bit>
			<bit unknown="yes" />
			<bit name="is_cathedral">
				<description>Is there a cathedral?</description>
			</bit>

			<bit unknown="yes" />
			<bit name="is_no_fortress">
				<description>Is there no city fortress?</description>
				<notes>
					<note>A rare case of a reversed boolean.  Possibly it's a "has something else" flag, and fortresses are added if it doesn't have the other?</note>
				</notes>
			</bit>
			<bit name="is_town_hall">
				<description>Is there a town hall?</description>
			</bit>
			<bit name="is_polit" constant="yes" value="1">
				<description>Is there a political center?</description>
			</bit>

			<bit constant="yes" value="0" />
			<bit constant="yes" value="0" />
			<bit constant="yes" value="0" />
			<bit constant="yes" value="0" />

			<bit name="docks">
				<description>Are there docks?</description>
			</bit>
			<bit unknown="yes" />
			<bit name="is_pawnshop">
				<description>Is there a liefhaus (pawnshop)?</description>
			</bit>
			<bit name="is_university">
				<description>Is there a university?</description>
			</bit>
		</bitmask>

		<word at="0x20" constant="yes" value="0" />

		<byte at="0x22" name="qual_black">
			<description>Quality of the blacksmith.</description>
			<notes>
				<note>
					This, and the other nine qualities, all seem to work in the same way.
				</note>
				<note>A zero value indicates that the city does not have that particular shop.</note>
				<note>
					Non-zero values do not exactly equal the quality of the items available,
					but merely indicate relative qualities!
					For example, Nurnberg has a 0x31 (49) listed for the armory, but offers q37 (0x25) armor.
					However, if one city has a higher value than another, then that city's items
					will be of equal or greater quality.
				</note>
				<note>
					The quality of the healer is not stored here, but is apparently random.  (TODO: verify?)
				</note>
				<note>
					TODO: comments about Quality of the alchemist, university, pharmacist being the seed thing.
				</note>
			</notes>
		</byte>

		<byte at="0x23" name="qual_merch">
			<description>Quality of the merchant.</description>
		</byte>
		<byte at="0x24" name="qual_sword">
			<description>Quality of the swordsmith.</description>
		</byte>
		<byte at="0x25" name="qual_armor">
			<description>Quality of the armorer.</description>
		</byte>

		<byte at="0x26" name="qual_unk1" unknown="yes" />

		<byte at="0x27" name="qual_bow">
			<description>Quality of the bowyer.</description>
		</byte>
		<byte at="0x28" name="qual_tink">
			<description>Quality of the tinker.</description>
		</byte>

		<byte at="0x29" name="qual_unk2" unknown="yes" />

		<byte at="0x2a" name="qual_cloth">
			<description>Quality of the clothing merchant.</description>
		</byte>

		<byte at="0x2b" constant="yes" value="0" />

		<byte at="0x2c" unknown="yes">
			<notes>
				<note>Since the following byte is 0 or 1, this and that might actually be a single word value.</note>
			</notes>
		</byte>

		<byte at="0x2d" unknown="yes">
			<notes>
				<note>Either zero or one (only a couple of ones).</note>
			</notes>
		</byte>
	</structdef>
</structdefs>

<enumerations>
	<enumeration type="ruler">
		<description>Type of city (free, ruled, capital)</description>
		<notes>
			<note>This controls which message from <html:code>$CITYE00.msg</html:code> is given when you are approaching a city.</note>
		</notes>
		<map from="0" to="Free City">
			<notes>
				<note>Message 7</note>
			</notes>
		</map>
		<map from="1" to="Ruled City">
			<notes>
				<note>Message 1</note>
			</notes>
		</map>
		<map from="2" to="Capital">
			<notes>
				<note>Message 6</note>
			</notes>
		</map>
	</enumeration>
</enumerations>

</file>
