=== rhaul/Darklands/file_formats/wallace.net/darklands/xml_formats/file_format.dtd
<!-- Root element: the file -->
<!ELEMENT file (globs?, description, notes?, offsets?, structdefs?, enumerations?, ignore?)>
<!ATTLIST file
	name CDATA #REQUIRED
>

<!-- ====================================================================== -->

<!-- External definitions of a "simple HTML subset" -->
<!ENTITY % SimpleHTML SYSTEM "simple_inline_html.dtd">
%SimpleHTML;

<!-- ====================================================================== -->

<!-- Data types -->

<!ENTITY % BasicVar.Class "char | byte | word | dword | bit">

<!ENTITY % SizableVar.Class "int | string">

<!ENTITY % ContainerVar.Class "struct | array | bitmask">

<!-- All data types (including the unknown object) -->

<!ENTITY % Var.Class "
	%BasicVar.Class; |
	%SizableVar.Class; |
	%ContainerVar.Class; |
	unknown
">

<!-- ====================================================================== -->

<!ENTITY % Describable.Contents "
	description?, notes?
">

<!-- Contents of the basic data types -->
<!ENTITY % BasicVar.Contents "
	( %Describable.Contents; )
">

<!ENTITY % SizableVar.Contents "
	%BasicVar.Contents;
">

<!-- ====================================================================== -->

<!-- Filename glob for instances of this file type -->
<!ELEMENT globs (glob+)>
<!ELEMENT glob EMPTY>
<!ATTLIST glob
	dir CDATA #IMPLIED
	filespec CDATA #REQUIRED
>

<!-- Expected contents at a particular offset -->
<!ELEMENT offsets (offset+)>
<!ELEMENT offset ((%Var.Class;)*)>
<!ATTLIST offset
	start CDATA #REQUIRED
	end CDATA #IMPLIED
>

<!-- Definition of a structure -->
<!ELEMENT structdefs (structdef | external-structdef)+>
<!ELEMENT structdef (%Describable.Contents;, (%Var.Class;)*)>
<!ATTLIST structdef
	type ID #REQUIRED
	description CDATA #IMPLIED
	size CDATA #IMPLIED
>
<!ELEMENT external-structdef EMPTY>
<!ATTLIST external-structdef
	type ID #REQUIRED
	file CDATA #REQUIRED
>

<!-- Definition of an enumeration mapping -->
<!ELEMENT enumerations (enumeration | external-enumeration)+>
<!ELEMENT enumeration (%Describable.Contents;, map*)>
<!ATTLIST enumeration
	type ID #REQUIRED
	description CDATA #IMPLIED
>
<!ELEMENT external-enumeration EMPTY>
<!ATTLIST external-enumeration
	type ID #REQUIRED
	file CDATA #REQUIRED
>

<!--
	Extra text at the end of the file which can be ignored.
	Intended to be used only while still developing a file format document.
-->
<!ELEMENT ignore (#PCDATA)>

<!-- ====================================================================== -->

<!-- Default attributes of all known data types -->
<!ENTITY % Var.Attrib "
	at CDATA #IMPLIED
	name CDATA #IMPLIED
	label NMTOKEN #IMPLIED
	unknown ( yes | no ) #IMPLIED
	constant ( yes | no ) #IMPLIED
	value CDATA #IMPLIED
">

<!-- Attributes of a basic data element -->
<!ENTITY % BasicVar.Attrib "
	%Var.Attrib;
	enumeration NMTOKEN #IMPLIED
">

<!-- Additional attributes of a sizable data element (like 'string') -->
<!ENTITY % SizableVar.Attrib "
	%Var.Attrib;
	size CDATA #IMPLIED
">

<!-- ====================================================================== -->

<!-- Simple (non-container) data types -->

<!ELEMENT char %BasicVar.Contents;>
<!ATTLIST char
	%BasicVar.Attrib; 
>
<!ELEMENT byte %BasicVar.Contents;>
<!ATTLIST byte
	%BasicVar.Attrib; 
>
<!ELEMENT word %BasicVar.Contents;>
<!ATTLIST word
	%BasicVar.Attrib; 
>
<!ELEMENT dword %BasicVar.Contents;>
<!ATTLIST dword
	%BasicVar.Attrib; 
>
<!ELEMENT bit %BasicVar.Contents;>
<!ATTLIST bit
	%BasicVar.Attrib; 
>

<!-- ====================================================================== -->

<!ELEMENT int %SizableVar.Contents;>
<!ATTLIST int
	%SizableVar.Attrib; 
>

<!ELEMENT string %SizableVar.Contents;>
<!ATTLIST string
	%SizableVar.Attrib; 
	enumeration NMTOKEN #IMPLIED
	delimiter CDATA #IMPLIED
>

<!-- ====================================================================== -->

<!-- Container data types -->

<!ELEMENT struct (%Describable.Contents;)>
<!ATTLIST struct
	%BasicVar.Attrib; 
	type IDREF #REQUIRED
>

<!ELEMENT array (%Describable.Contents;, (%Var.Class;))>
<!ATTLIST array
	%BasicVar.Attrib; 
	%SizableVar.Attrib; 
>

<!ELEMENT bitmask (%Describable.Contents;, (bit, bit, bit, bit, bit, bit, bit, bit)+)>
<!ATTLIST bitmask
	%BasicVar.Attrib; 
	%SizableVar.Attrib; 
>

<!-- ====================================================================== -->

<!ELEMENT unknown (%Describable.Contents;, guesses?)>
<!ATTLIST unknown
	at CDATA #IMPLIED
	size CDATA #IMPLIED
	constant (yes | no) #IMPLIED
	value CDATA #IMPLIED
>

<!ELEMENT guesses (guess+)>
<!ELEMENT guess (%Describable.Contents;, (%Var.Class;)*)>

<!-- ====================================================================== -->

<!-- Description (of a file, element, struct, etc) -->
<!ELEMENT description (%html.flow; | reference)*>
<!ATTLIST description
	type (simple | paragraph | extended) #IMPLIED
	xmlns:html CDATA #FIXED "http://www.w3.org/1999/xhtml"
>

<!-- Notes and comments (informal additions to the description) -->
<!ELEMENT notes (note+)>
<!ELEMENT note (#PCDATA | %html.inline; | reference)*>
<!ATTLIST note
	xmlns:html CDATA #FIXED "http://www.w3.org/1999/xhtml"
>

<!-- Reference to an internal or external definition -->
<!ELEMENT reference (#PCDATA)>
<!ATTLIST reference
	file CDATA #IMPLIED
	type CDATA #IMPLIED
	to NMTOKEN #IMPLIED
	label CDATA #IMPLIED
>

<!-- ====================================================================== -->

<!-- A mapping (part of an enumeration) -->
<!ELEMENT map (notes?)>
<!ATTLIST map
	from CDATA #REQUIRED
	to CDATA #REQUIRED
>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/X.fnt.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Font definition files">

<globs>
	<glob filespec="fonts.*" />
</globs>

<description type="paragraph">
	Font definitions.
    There are two font files. Fonts.fnt (game fonts) and fonts.utl (editor fonts?).
</description>

<offsets>
	<offset start="0x00">

        <word at="0x00" name="font_count" value="0x3">
        <description>Number of contained fonts</description>
        </word>

		<array at="0x02" name="font_data_offsets" size="0x03">
			<word />
			<description>Offsets of font data start in file.</description>
			<notes>
				<note>This is start of pixel data. Font header precedes it.</note>
			</notes>
		</array>
	</offset>

</offsets>

<!-- ====================================================================== -->

<structdefs>
	<structdef type="font_definition" size="variable">

		<byte at="font_data_offset - 0x08" name="start_char_code">
			<description>Ascii code of the first font character.</description>
		</byte>
		<byte at="font_data_offset - 0x7" name="end_char_code">
			<description>Ascii code of the last font character.</description>
		</byte>
        <byte at="font_data_offset - 0x6" name="char_data_width">
            <description>Character data width in bytes.</description>
        </byte>
        <byte at="font_data_offset - 0x5" unknown="yes" value="0"/>
        <byte at="font_data_offset - 0x4" name="char_height">
            <description>Character height.</description>
        </byte>
        <byte at="font_data_offset - 0x3" name="char_spacing" value="1">
            <description>Space between characters (px).</description>
        </byte>
        <byte at="font_data_offset - 0x2" name="line_spacing" value="1">
            <description>Space between lines (px).</description>
        </byte>
        <byte at="font_data_offset - 0x1" unknown="yes" value="0"/>

        <array at="font_data_offset - 8 - size" size="end_char_code - start_char_code + 1" name="character_width">
            <byte />
            <description>Font characters widths</description>
            <notes>
                <note>Precedes font header.</note>
            </notes>
        </array>

		<array at="font_data_offset" size="character_count * char_data_width * char_height" name="font_data">
			<byte />
			<description>Font pixel data</description>
			<notes>
				<note>Font char pixels are stored as bits.</note>
				<note>Ie. char_data_width = 2, char_height=8: ([char1_byte]*2[char2_byte]*2 ...)*8</note>
			</notes>
		</array>
	</structdef>
</structdefs>

</file>

=== rhaul/Darklands/file_formats/wallace.net:80/darklands/xml_formats/enumerations.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands common enumerations">

<description>These enumerations are common to a number of different files.</description>

<enumerations>

	<enumeration type="image_group">
		<description>Image group for battlefield images and animations.</description>
		<notes>
			<note>
				Usually represented as three characters followed by a null,
				although in some places spaces are used instead of nulls.
			</note>
			<note>An initial 'E' stands for a non-player human, an 'M' for a nonhuman.</note>
		</notes>
		<map from="A00" to="player character: alchemist" />
		<map from="C00" to="player character: cleric" />
		<map from="F01" to="player character: male fighter" />
		<map from="F60" to="player character: female fighter" />
		<map from="E00" to="human: Sergeant" />
		<map from="E02" to="human: Guard" />
		<map from="E03" to="human: Bandit" />
		<map from="E04" to="human: Mercenary" />
		<map from="E05" to="human: GrayExPC" />
		<map from="E06" to="human: Evil Alchemist or Kobold King" />
		<map from="E07" to="human: BrunExPC" />
		<map from="E08" to="human: High Witch or Acolyte" />
		<map from="E09" to="human: Monk" />
		<map from="E10" to="human: Knight" />
		<map from="E11" to="human: TinKnight" />
		<map from="E12" to="human: BlondExPC" />
		<map from="E13" to="human: Templar or Preceptor" />
		<map from="E17" to="human: Witch Cultist or Acolyte" />
		<map from="M00" to="non-human: Wolf" />
		<map from="M01" to="non-human: Boar" />
		<map from="M02" to="non-human: Dwarf" />
		<map from="M03" to="non-human: Skeleton" />
		<map from="M04" to="non-human: Gnome" />
		<map from="M05" to="non-human: Gargoyle" />
		<map from="M06" to="non-human: Kobold" />
		<map from="M07" to="non-human: Vulcan" />
		<map from="M08" to="non-human: Undead" />
		<map from="M09" to="non-human: Dwarf Overseer or Master" />
		<map from="M10" to="non-human: Giant Gnome" />
		<map from="M11" to="non-human: DemonTh" />
		<map from="M12" to="non-human: DemonKt" />
		<map from="M13" to="non-human: DemonPrn" />
		<map from="M14" to="non-human: Demon Locust" />
		<map from="M20" to="non-human: Big Spider" />
		<map from="M21" to="non-human: Bear" />
		<map from="M22" to="non-human: Tatzelwurm" />
		<map from="M40" to="non-human: Wild Hunter" />
		<map from="M41" to="non-human: Hellhound" />
		<map from="M42" to="non-human: Schrat" />
		<map from="M73" to="non-human: 7 Headed Dragon" />
		<map from="M90" to="non-human: Cave Dragon" />
		<map from="M99" to="non-human: Baphomet" />
	</enumeration>

	<enumeration type="menu">
		<description>The current menu of options.</description>
		<notes>
			<note>
				This defines which menu of options you get
				(which determines the background image and possibly the music).
				Any place there is a menu is represented in here:
				in-city menus, encounters, talking to the miners, even the iron doors in the mines.
			</note>
			<note>
				These definitions may be stored in the executable; they haven't been found elsewhere.
				A 'strings' of darkland.exe reveals a bunch of names that look like the menus, in the appropriate order, but no simple structure was apparent -- other binary data was in there too.
			</note>
			<note>These are possibly called 'cards' internally to the game.</note>
			<note>
				When travelling on the map, 0x0c is used (which isn't really a 'menu of options').
			</note>
		</notes>

		<map from="0x0c" to="Darklands map (travelling)" />
		<map from="TODO!" to="TODO!" />
	</enumeration>

	<enumeration type="month">
		<description>Calendar month.</description>
		<notes>
			<note>Months are zero-based</note>
		</notes>
		<map from="0" to="January" />
		<map from="1" to="February" />
		<map from="2" to="March" />
		<map from="3" to="April" />
		<map from="4" to="May" />
		<map from="5" to="June" />
		<map from="6" to="July" />
		<map from="7" to="August" />
		<map from="8" to="September" />
		<map from="9" to="October" />
		<map from="10" to="November" />
		<map from="11" to="December" />
	</enumeration>

</enumerations>

</file>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/locs.tmp.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands current location data">

<globs>
	<glob filespec="locs.tmp" />
</globs>

<description type="extended">
	<html:p>
	This is a temporary file, created when a saved game is loaded.
	TODO: is this also created when a new game is started?  Or when going in and out of battle?
	</html:p>

	<html:p>
	All of the structures in here are defined in the saved game format,
	so only brief descriptions are given here.
	</html:p>
</description>

<offsets>
	<offset start="0x00" end="0x5dcd">
		<word at="0x00" name="num_locations" value="0x19e">
			<notes>
				<note>
					See <reference type="variable" to="num_locations" file="dksaveXX.sav" />.
				</note>
			</notes>
		</word>

		<array at="0x02" size="*num_locations" name="locations">
			<notes>
				<note>
					See <reference type="variable" to="locations" file="dksaveXX.sav" />.
				</note>
			</notes>
			<struct type="location" />
		</array>
	</offset>
</offsets>

<!-- ====================================================================== -->

<structdefs>
	<external-structdef type="location" file="dksaveXX.sav" />
</structdefs>

</file>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/darkland.alc.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands alchemical formulae">

<globs>
	<glob filespec="darkland.alc" />
</globs>

<description>Contains descriptions, ingredients, and other values for alchemical formulae.</description>

<offsets>
	<offset start="0x00">
		<byte at="0x00" name="num_formulae" value="0x42">
			<description>Number of formula definitions.</description>
		</byte>

		<array at="0x01" size="*num_formulae" name="formula_definitions">
			<description>Formula definitions.</description>
			<notes>
				<note>
					The order of formulas here matches the order in
					<reference file="darkland.lst" type="variable" to="formula_full_names" />.
				</note>
			</notes>
			<struct type="formula_definition" />
		</array>
	</offset>
</offsets>

<!-- ====================================================================== -->

<structdefs>

	<structdef type="formula_definition" size="0x68">
		<description>A definition of an alchemical formula.</description>

		<string at="0x00" size="80" name="description">
			<description>Text description of the formula.</description>
			<notes>
				<note>The last character is always a null, as is any unused space</note>
			</notes>
		</string>

		<word at="0x50" name="mystic_number">
			<description>Mystic number (the base difficulty when mixing a new potion).</description>
		</word>

		<word at="0x52" name="risk_factor">
			<description>Risk factor (when mixing a new potion).</description>
			<notes>
				<note>0=low, 1=medium, 2=high.</note>
			</notes>
		</word>

		<array at="0x54" size="5" name="ingredients">
			<description>Ingredients required to mix a potion.</description>
			<notes>
				<note>Ingredients are given in increasing item code value</note>
				<note>If fewer than 5 ingredients are needed, the remaining space in the array is filled with zeroes.</note>
			</notes>
			<struct type="ingredient" />
		</array>
	</structdef>

	<structdef type="ingredient" size="4">
		<description>An ingredient (and quantity) for an alchemical formula.</description>

		<word at="0x00" name="quantity">
			<description>The amount of this ingredient needed.</description>
			<notes>
				<note>Ranges from 1-5.</note>
			</notes>
		</word>
		<word at="0x02" name="item_code">
			<description>The item code of the ingredient.</description>
			<notes>
				<note>Ingredients are given in increasing item code value.</note>
				<note>
					Codes are a reference to offsets into the 
					<reference type="variable" to="item_definitions" file="darkland.lst">item_definitions array</reference>.
				</note>
			</notes>
		</word>
	</structdef>

</structdefs>

</file>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/darkland.loc.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands location definitions">

<globs>
	<glob filespec="darkland.loc" />
</globs>

<description type="paragraph">
	Contains names, coordinates, and other data for all map locations.
	This data is copied into each saved game file.
</description>

<offsets>
	<offset start="0x00">
		<word at="0x00" name="num_locations" value="0x19e">
			<description>Number of locations.</description>
		</word>
		<array at="0x02" size="*num_locations" name="locations">
			<description>Location definitions.</description>
			<struct type="location" />
		</array>
	</offset>
</offsets>

<!-- ====================================================================== -->

<structdefs>
	<external-structdef type="coordinates" file="structures" />

	<structdef type="location" size="0x3a">
		<word at="0x00" name="icon" enumeration="location_icon">
			<description>Map image for the location.</description>
			<notes>
				<note>Note that this basically corresponds to the 'type' of location.</note>
			</notes>
		</word>

		<word at="0x02" unknown="yes">
			<notes>
				<note>0 for cities, other locations range from 0x08-0x0e.</note>
			</notes>
		</word>

		<struct at="0x04" type="coordinates" name="coords">
			<description>Map coordinates.</description>
		</struct>

		<word at="0x08" unknown="yes">
			<notes>
				<note>Ranges from 1-10.</note>
				<note>Seems to be 4 or 9 for live Raubritters (1 for dead); perhaps it's a strength?</note>
			</notes>
		</word>

		<word at="0x0a" unknown="yes">
			<notes>
				<note>Most range from 1-5, except pagan altars, which are 0x63 (99).</note>
			</notes>
		</word>

		<word at="0x0c" name="menu" enumeration="menu">
			<description>Card displayed on entering the location.</description>
			<notes>
				<note>
					This is the 
					<reference type="enumeration" to="menu" file="enumerations" />
					(card, screen?) you get when you enter the location.
				</note>
				<note>
					It could be said that this is the closest thing to a "location type" that there is.
				</note>
			</notes>
		</word>

		<word at="0x0e" unknown="yes">
			<notes>
				<note>
					Always 0x62 except for castles currently occupied by Raubritters
					(<reference type="variable" to="icon" />=2); those are 0x92.
				</note>
			</notes>
		</word>

		<byte at="0x10" unknown="yes" constant="yes" value="0xff" />

		<byte at="0x11" name="city_size">
			<description>Size of the city.</description>
			<notes>
				<note>Cities range from 3 (small) to 8 (Koln); non-cities are always 1.</note>
			</notes>
		</byte>

		<word at="0x12" name="local_rep">
			<description>Local reputation.</description>
			<notes>
				<note>
					In this file, this is always zero.  The copy of this structure that lives in the
					<reference file="dksaveXX.sav">saved game files</reference> gets non-zero values.
				</note>
				<note>Ranges from -150 to 150 (although others claim to have observed numbers outside this range).</note>
			</notes>
		</word>

		<byte at="0x14" unknown="yes">
			<notes>
				<note>Zero seems to indicate an "active" site.</note>
				<note>Ruins of a Raubritter castle get 0x04, as do destroyed villages.</note>
				<note>Some other locations get 0x20 or 0x24.</note>
			</notes>
		</byte>

		<unknown at="0x15" size="3" constant="yes" value="{ 0x19, 0x19, 0x19 }" />

		<word at="0x18" name="inn_cache_idx">
			<notes>
				<note>In this file, this is always 0xffff (-1).</note>
				<note>
					In a saved game file, if the party stores items at an inn (in a city), this
					value becomes an index into
					<reference type="variable" to="cache_offsets" file="dksaveXX.sav" />.
				</note>
			</notes>
		</word>

		<word at="0x19" constant="yes" value="0x0000" />

		<word at="0x1b" unknown="yes">
			<notes>
				<note>
					All are zero except for Nurnberg, which is 0xc0.
				</note>
			</notes>
		</word>

		<unknown at="0x1d" size="8" constant="yes" value="all 0x00" />

		<string at="0x25" size="20" name="name">
			<description>Name.</description>
		</string>
	</structdef>

</structdefs>

<!-- ====================================================================== -->

<enumerations>

	<external-enumeration type="menu" file="enumerations" />

	<enumeration type="location_icon">
		<description>Map image for the location.</description>
		<notes>
			<note>Darklands keeps the images and the menu options tied together, so the 'image' for a location is pretty much the indicator of the 'type' of location.</note>
			<note>Any unlisted values are displayed as the standard 'castle' style image.</note>
		</notes>
		<map from="0x00" to="city" />
		<map from="0x01" to="castle (lord or evil lord variety)" />
		<map from="0x02" to="castle (Raubritter variety)" />
		<map from="0x03" to="monastery" />
		<map from="0x04" to="(looks like tomb or pagan altar) TODO: Teufelstein is one" />
		<map from="0x05" to="cave (TODO: what kind?)" />
		<map from="0x06" to="mines" />
		<map from="0x08" to="village" />
		<map from="0x09" to="ruins of a village" />
		<map from="0x0a" to="village (more square than 0x08, and unused?)" />
		<map from="0x0d" to="tomb" />
		<map from="0x0f" to="dragon's lair (invisible; cannot interact?)" />
		<map from="0x10" to="spring" />
		<map from="0x11" to="lake" />
		<map from="0x12" to="shrine" />
		<map from="0x13" to="cave (TODO: what kind?)" />
		<map from="0x14" to="pagan altar" />
		<map from="0x15" to="witch sabbat" />
		<map from="0x16" to="Templar castle (has a black top)" />
		<map from="0x17" to="Hockkonig (the Baphomet castle; all gray)" />
		<map from="0x18" to="alpine cave" />
		<map from="0x19" to="lady of the lake (magician/astrologer)" />
		<map from="0x1a" to="ruins of a Raubritter's castle" />
	</enumeration>
</enumerations>

</file>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/enemypal.dat.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Enemy sprite palettes file">

<globs>
	<glob filespec="enemypal.dat" />
</globs>

<description type="paragraph">
	Small palette chungs (16 RGB triplets) used for enemy IMC rendering.
</description>

<offsets>
	<offset start="0x00">
		<array at="0x00" name="palettes" size="0x47">
			<struct type="palette_chunk"/>
			<description>Offsets of font data start in file.</description>
		</array>
	</offset>

</offsets>

<!-- ====================================================================== -->

<structdefs>
	<structdef type="palette_chunk" size="0x34">

		<byte at="0x00" name="start_offset">
			<description>Starting palette triplets offset</description>
			<notes>
                <note>Divide by 3 to get palette index</note>
            </notes>
		</byte>
        <array at="0x01" size="0xf0" name="triplets">
            <byte />
            <description>RGB byte triplets</description>
            <notes>
                <note>Each component seems divided by 4 for reason unknown.</note>
            </notes>
        </array>
		<array at="0xf1" size="0x03" unknown="yes">
            <byte />
            <notes>
                <note>Sprites use 16 specific colors max. Ending triplet purpose is mystery.</note>
            </notes>
        </array>
	</structdef>
</structdefs>

</file>

=== rhaul/Darklands/file_formats/up-to-date/xml_formats/X.msg.xml
<?xml version="1.0"?>
<!DOCTYPE file SYSTEM "file_format.dtd">
<file name="Darklands message file">

<globs>
	<glob filespec="*.msg" />
</globs>

<description type="extended">
<html:p>
Contains text and possibly other information about screens (cards).
</html:p>
<html:p>
It is difficult to tell if a "card" refers to the entire file, or
to one of the string entries in the file.  The terms are confusingly
used interchangably in this file.
</html:p>
<html:p>
Most, if not all, "<html:code>.msg</html:code>" files are found within
the one cat file <html:a href="catalogs/msgfiles.html">msgfiles</html:a>.
</html:p>
</description>

<offsets>
	<offset start="0x00">
		<byte at="0x00" name="num_cards">
			<description>Number of cards.</description>
		</byte>

		<array at="0x01" size="*num_cards" name="card_definitions">
			<description>Card definitions.</description>
			<struct type="card" />
		</array>
	</offset>
</offsets>

<!-- ====================================================================== -->

<structdefs>

	<structdef type="card">
		<description>A definition of an alchemical formula.</description>

		<unknown at="0x00" size="5">
			<notes>
				<note>Many of these are {0x0a, 0x0a, 0x00, 0xf0, 0x00}.</note>
				<note>Possibly these have to do with colors, images, or music?</note>
			</notes>
		</unknown>
		<string at="0x05" name="contents" delimiter="null">
			<description>Textual contents of the screen.</description>
			<notes>
				<note>
					Screens are always a preamble of text, sometimes followed by a list of up to ten options.
					If there are not that many choices, bogus entries (usually just numbered 1-10) fill the option slots.
				</note>
				<note>
					Some cards appear to be standardized (always ten options, with potion/saint/leave options in the same places).
				</note>

				<note>
					0x0a seems to be a newline, 0x14 seems to be a paragraph break.
					These are almost always used together as a pair {0x0a, 0x14},
					between every paragraph and each option.
				</note>
				<note>Usually the valid options start with {0x0a, 0x14}, but sometimes have an extra 0x14 or 0x15 appended (spacing?).</note>
				<note>0x15 is unknown.  Usually it follows the {0x0a, 0x14}, so it's probably whitespace?</note>
				<note>There is always an 0x1d between the "..." and the text of an option.</note>
				<note>An 0x10 immediately precedes the "..." for options that offer a popup potion selection.</note>
				<note>An 0x16 immediately precedes the "..." for options that offer a popup saint selection.</note>
				<note>An 0x06 immediately precedes the "..." for options that would cause the party to enter battle immediately.</note>
			</notes>
		</string>
	</structdef>

</structdefs>

</file>
